from __future__ import annotations

import argparse
from pathlib import Path

from config import EA_EXPORT_PATH, EXPORTS_DIR, ensure_directories
from strategy_schema import load_strategy


EA_TEMPLATE = """// EA_XAU_HYBRID.mq5
// Generated by AI_GOLD_RESEARCH.
// Strategy: {name}
// Research target: XAUUSD hybrid breakout, M5 entry, 1% risk, spread-aware research.
#property strict

#include <Trade/Trade.mqh>
CTrade trade;

input string InpSymbol = "{symbol}";
input double InpRiskPercent = {risk_percent:.4f};
input int InpFastMA = {fast_ma};
input int InpSlowMA = {slow_ma};
input int InpTrendMA = {trend_ma};
input int InpATRPeriod = {atr_period};
input double InpATRStopMultiplier = {atr_stop_multiplier:.8f};
input double InpRewardRisk = {reward_risk:.8f};
input int InpBreakoutLookback = {breakout_lookback};
input int InpSessionStartUTC = {session_start_utc};
input int InpSessionEndUTC = {session_end_utc};
input int InpMaxTradesPerDay = {max_trades_per_day};
input int InpMaxHoldingHours = {max_holding_hours};
input long InpMagic = 26062120;
input bool InpAllowLong = {allow_long};
input bool InpAllowShort = {allow_short};
input bool InpUseConfirmationFilter = {use_confirmation_filter};
input bool InpUseTrendFilter = {use_trend_filter};
input bool InpOnePositionAtTime = true;

datetime last_bar_time = 0;
int trades_today = 0;
int day_key = -1;

int OnInit()
{{
   trade.SetExpertMagicNumber(InpMagic);
   return INIT_SUCCEEDED;
}}

void OnTick()
{{
   string symbol = InpSymbol;
   if(!SymbolSelect(symbol, true))
      return;

   ManageTimeExit(symbol);

   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   int needed = MathMax(InpBreakoutLookback + 3, InpSlowMA + 3);
   if(CopyRates(symbol, PERIOD_M5, 0, needed, rates) < needed)
      return;

   if(rates[0].time == last_bar_time)
      return;
   last_bar_time = rates[0].time;

   UpdateDailyCounter();
   if(trades_today >= InpMaxTradesPerDay)
      return;

   MqlDateTime utc;
   TimeToStruct(TimeGMT(), utc);
   if(utc.hour < InpSessionStartUTC || utc.hour >= InpSessionEndUTC)
      return;

   if(InpOnePositionAtTime && HasOpenPosition(symbol))
      return;

   double atr = GetATR(symbol, PERIOD_M5, InpATRPeriod);
   if(atr <= 0)
      return;

   double breakout_high = rates[2].high;
   double breakout_low = rates[2].low;
   for(int i = 2; i < InpBreakoutLookback + 2; i++)
   {{
      breakout_high = MathMax(breakout_high, rates[i].high);
      breakout_low = MathMin(breakout_low, rates[i].low);
   }}

   double close_price = rates[1].close;
   bool long_signal = InpAllowLong && close_price > breakout_high;
   bool short_signal = InpAllowShort && close_price < breakout_low;

   if(long_signal && !PassLongFilters(symbol))
      long_signal = false;
   if(short_signal && !PassShortFilters(symbol))
      short_signal = false;

   if(long_signal)
      OpenTrade(symbol, ORDER_TYPE_BUY, atr);
   else if(short_signal)
      OpenTrade(symbol, ORDER_TYPE_SELL, atr);
}}

double GetATR(string symbol, ENUM_TIMEFRAMES timeframe, int period)
{{
   int handle = iATR(symbol, timeframe, period);
   if(handle == INVALID_HANDLE)
      return 0.0;
   double buffer[];
   ArraySetAsSeries(buffer, true);
   if(CopyBuffer(handle, 0, 1, 1, buffer) != 1)
   {{
      IndicatorRelease(handle);
      return 0.0;
   }}
   IndicatorRelease(handle);
   return buffer[0];
}}

double GetMA(string symbol, ENUM_TIMEFRAMES timeframe, int period)
{{
   int handle = iMA(symbol, timeframe, period, 0, MODE_SMA, PRICE_CLOSE);
   if(handle == INVALID_HANDLE)
      return 0.0;
   double buffer[];
   ArraySetAsSeries(buffer, true);
   if(CopyBuffer(handle, 0, 1, 1, buffer) != 1)
   {{
      IndicatorRelease(handle);
      return 0.0;
   }}
   IndicatorRelease(handle);
   return buffer[0];
}}

bool GetLastClose(string symbol, ENUM_TIMEFRAMES timeframe, double &close_value)
{{
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   if(CopyRates(symbol, timeframe, 1, 1, rates) != 1)
      return false;
   close_value = rates[0].close;
   return true;
}}

bool PassLongFilters(string symbol)
{{
   if(InpUseConfirmationFilter)
   {{
      double close_m15 = 0.0;
      double ma_m15 = GetMA(symbol, PERIOD_M15, InpSlowMA);
      if(!GetLastClose(symbol, PERIOD_M15, close_m15) || ma_m15 <= 0 || close_m15 <= ma_m15)
         return false;
   }}
   if(InpUseTrendFilter)
   {{
      double close_h1 = 0.0;
      double ma_h1 = GetMA(symbol, PERIOD_H1, InpTrendMA);
      if(!GetLastClose(symbol, PERIOD_H1, close_h1) || ma_h1 <= 0 || close_h1 <= ma_h1)
         return false;
   }}
   return true;
}}

bool PassShortFilters(string symbol)
{{
   if(InpUseConfirmationFilter)
   {{
      double close_m15 = 0.0;
      double ma_m15 = GetMA(symbol, PERIOD_M15, InpSlowMA);
      if(!GetLastClose(symbol, PERIOD_M15, close_m15) || ma_m15 <= 0 || close_m15 >= ma_m15)
         return false;
   }}
   if(InpUseTrendFilter)
   {{
      double close_h1 = 0.0;
      double ma_h1 = GetMA(symbol, PERIOD_H1, InpTrendMA);
      if(!GetLastClose(symbol, PERIOD_H1, close_h1) || ma_h1 <= 0 || close_h1 >= ma_h1)
         return false;
   }}
   return true;
}}

bool HasOpenPosition(string symbol)
{{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) == symbol && PositionGetInteger(POSITION_MAGIC) == InpMagic)
         return true;
   }}
   return false;
}}

void UpdateDailyCounter()
{{
   MqlDateTime utc;
   TimeToStruct(TimeGMT(), utc);
   int current_key = utc.year * 10000 + utc.mon * 100 + utc.day;
   if(current_key != day_key)
   {{
      day_key = current_key;
      trades_today = 0;
   }}
}}

void OpenTrade(string symbol, ENUM_ORDER_TYPE order_type, double atr)
{{
   double stop_distance = atr * InpATRStopMultiplier;
   if(stop_distance <= 0)
      return;

   double price = (order_type == ORDER_TYPE_BUY) ? SymbolInfoDouble(symbol, SYMBOL_ASK) : SymbolInfoDouble(symbol, SYMBOL_BID);
   double sl = (order_type == ORDER_TYPE_BUY) ? price - stop_distance : price + stop_distance;
   double tp = (order_type == ORDER_TYPE_BUY) ? price + stop_distance * InpRewardRisk : price - stop_distance * InpRewardRisk;
   double lots = CalculateLots(symbol, stop_distance);
   if(lots <= 0)
      return;

   bool ok = false;
   if(order_type == ORDER_TYPE_BUY)
      ok = trade.Buy(lots, symbol, price, sl, tp, "AI_GOLD_RESEARCH breakout");
   else
      ok = trade.Sell(lots, symbol, price, sl, tp, "AI_GOLD_RESEARCH breakout");

   if(ok)
      trades_today++;
}}

double CalculateLots(string symbol, double stop_distance)
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_money = balance * InpRiskPercent / 100.0;
   double tick_size = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   double tick_value = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double volume_min = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double volume_max = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   double volume_step = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   if(tick_size <= 0 || tick_value <= 0 || volume_step <= 0)
      return 0.0;

   double risk_per_lot = (stop_distance / tick_size) * tick_value;
   if(risk_per_lot <= 0)
      return 0.0;

   double lots = risk_money / risk_per_lot;
   lots = MathFloor(lots / volume_step) * volume_step;
   lots = MathMax(volume_min, MathMin(volume_max, lots));
   return lots;
}}

void ManageTimeExit(string symbol)
{{
   datetime now = TimeCurrent();
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != symbol || PositionGetInteger(POSITION_MAGIC) != InpMagic)
         continue;
      datetime open_time = (datetime)PositionGetInteger(POSITION_TIME);
      if(now - open_time >= InpMaxHoldingHours * 3600)
         trade.PositionClose(ticket);
   }}
}}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export selected research strategy to an MQ5 EA template.")
    parser.add_argument("--strategy", default="strategies/target_loop_best_strategy.json")
    parser.add_argument("--output", default=str(EA_EXPORT_PATH))
    parser.add_argument("--broker-symbol", help="Override the EA input symbol for a broker-specific export.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ensure_directories()
    strategy_path = Path(args.strategy)
    if not strategy_path.is_absolute():
        strategy_path = Path.cwd() / strategy_path
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = Path.cwd() / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)

    strategy = load_strategy(strategy_path)
    symbol = args.broker_symbol or strategy.symbol
    rendered = EA_TEMPLATE.format(
        name=strategy.name,
        symbol=symbol,
        risk_percent=strategy.risk_per_trade * 100,
        fast_ma=strategy.fast_ma,
        slow_ma=strategy.slow_ma,
        trend_ma=strategy.trend_ma,
        atr_period=strategy.atr_period,
        atr_stop_multiplier=strategy.atr_stop_multiplier,
        reward_risk=strategy.reward_risk,
        breakout_lookback=strategy.breakout_lookback,
        session_start_utc=strategy.session_start_utc,
        session_end_utc=strategy.session_end_utc,
        max_trades_per_day=strategy.max_trades_per_day,
        max_holding_hours=strategy.max_holding_hours,
        allow_long="true" if strategy.direction in {"both", "long"} else "false",
        allow_short="true" if strategy.direction in {"both", "short"} else "false",
        use_confirmation_filter="true" if strategy.use_confirmation_filter else "false",
        use_trend_filter="true" if strategy.use_trend_filter else "false",
    )
    output_path.write_text(rendered, encoding="utf-8")
    print(output_path)


if __name__ == "__main__":
    main()
