from __future__ import annotations

import json
from dataclasses import asdict

from backtest_engine import run_backtest, save_results
from config import BEST_STRATEGY_JSON, DATA_DIR, EA_EXPORT_PATH, M1_HISTORY_BARS, RESULTS_CSV, SERVER_TIME_REPORT, STRATEGIES_DIR, ensure_directories
from data_loader import build_timeframe_data, estimate_server_time_offset, get_m1_history, initialize_mt5, resolve_broker_symbol, save_server_time_report, shutdown_mt5
from evolution_engine import evolve
from strategy_generator import generate_strategy, save_strategy


def export_ea_placeholder(path, strategy: dict) -> None:
    # TODO: Generate production MQL5 after strategy validation and broker symbol settings are known.
    path.write_text(
        "\n".join(
            [
                "// EA_XAU_HYBRID.mq5",
                "// Starter export placeholder generated by AI_GOLD_RESEARCH.",
                "#property strict",
                "",
                "int OnInit() { return(INIT_SUCCEEDED); }",
                "void OnTick() {",
                f"  // TODO: Implement strategy: {strategy.get('name', 'unknown')}",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    ensure_directories()
    strategy = generate_strategy()
    save_strategy(strategy, STRATEGIES_DIR / f"{strategy.name}.json")

    initialize_mt5()
    try:
        broker_symbol = resolve_broker_symbol(strategy.symbol)
        server_time = estimate_server_time_offset(broker_symbol)
        save_server_time_report(server_time, SERVER_TIME_REPORT)
        m1_candles = get_m1_history(broker_symbol, bars=M1_HISTORY_BARS)
        m1_candles.to_csv(DATA_DIR / f"{broker_symbol}_M1_history.csv", index=False)
        frames = build_timeframe_data(
            m1_candles,
            [strategy.entry_timeframe, strategy.confirmation_timeframe, strategy.trend_timeframe],
        )
    finally:
        shutdown_mt5()

    offset = int(server_time.get("offset_hours", 0))
    backtest = run_backtest(frames, asdict(strategy), server_time_offset_hours=offset)
    evolution = evolve(frames, asdict(strategy))
    result = {**backtest, "evolution": json.dumps(evolution)}
    save_results(result, RESULTS_CSV, BEST_STRATEGY_JSON)
    export_ea_placeholder(EA_EXPORT_PATH, asdict(strategy))


if __name__ == "__main__":
    main()
