// EA_XAU_HYBRID.mq5
// Generated by AI_GOLD_RESEARCH.
// Strategy: target_loop_c1_t20
// Research target: XAUUSD hybrid breakout, M5 entry, 1% risk, spread-aware research.
#property strict

#include <Trade/Trade.mqh>
CTrade trade;

input string InpSymbol = "XAUUSD";
input double InpRiskPercent = 1.0000;
input int InpFastMA = 19;
input int InpSlowMA = 55;
input int InpATRPeriod = 5;
input double InpATRStopMultiplier = 2.27329556;
input double InpRewardRisk = 2.06330337;
input int InpBreakoutLookback = 10;
input int InpSessionStartUTC = 3;
input int InpSessionEndUTC = 20;
input int InpMaxTradesPerDay = 6;
input int InpMaxHoldingHours = 23;
input long InpMagic = 26062120;
input bool InpAllowLong = true;
input bool InpAllowShort = true;
input bool InpOnePositionAtTime = true;

datetime last_bar_time = 0;
int trades_today = 0;
int day_key = -1;

int OnInit()
{
   trade.SetExpertMagicNumber(InpMagic);
   return INIT_SUCCEEDED;
}

void OnTick()
{
   string symbol = InpSymbol;
   if(!SymbolSelect(symbol, true))
      return;

   ManageTimeExit(symbol);

   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   int needed = MathMax(InpBreakoutLookback + 3, InpSlowMA + 3);
   if(CopyRates(symbol, PERIOD_M5, 0, needed, rates) < needed)
      return;

   if(rates[0].time == last_bar_time)
      return;
   last_bar_time = rates[0].time;

   UpdateDailyCounter();
   if(trades_today >= InpMaxTradesPerDay)
      return;

   MqlDateTime utc;
   TimeToStruct(TimeGMT(), utc);
   if(utc.hour < InpSessionStartUTC || utc.hour >= InpSessionEndUTC)
      return;

   if(InpOnePositionAtTime && HasOpenPosition(symbol))
      return;

   double atr = GetATR(symbol, PERIOD_M5, InpATRPeriod);
   if(atr <= 0)
      return;

   double breakout_high = rates[2].high;
   double breakout_low = rates[2].low;
   for(int i = 2; i < InpBreakoutLookback + 2; i++)
   {
      breakout_high = MathMax(breakout_high, rates[i].high);
      breakout_low = MathMin(breakout_low, rates[i].low);
   }

   double close_price = rates[1].close;
   bool long_signal = InpAllowLong && close_price > breakout_high;
   bool short_signal = InpAllowShort && close_price < breakout_low;

   if(long_signal)
      OpenTrade(symbol, ORDER_TYPE_BUY, atr);
   else if(short_signal)
      OpenTrade(symbol, ORDER_TYPE_SELL, atr);
}

double GetATR(string symbol, ENUM_TIMEFRAMES timeframe, int period)
{
   int handle = iATR(symbol, timeframe, period);
   if(handle == INVALID_HANDLE)
      return 0.0;
   double buffer[];
   ArraySetAsSeries(buffer, true);
   if(CopyBuffer(handle, 0, 1, 1, buffer) != 1)
   {
      IndicatorRelease(handle);
      return 0.0;
   }
   IndicatorRelease(handle);
   return buffer[0];
}

bool HasOpenPosition(string symbol)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) == symbol && PositionGetInteger(POSITION_MAGIC) == InpMagic)
         return true;
   }
   return false;
}

void UpdateDailyCounter()
{
   MqlDateTime utc;
   TimeToStruct(TimeGMT(), utc);
   int current_key = utc.year * 10000 + utc.mon * 100 + utc.day;
   if(current_key != day_key)
   {
      day_key = current_key;
      trades_today = 0;
   }
}

void OpenTrade(string symbol, ENUM_ORDER_TYPE order_type, double atr)
{
   double stop_distance = atr * InpATRStopMultiplier;
   if(stop_distance <= 0)
      return;

   double price = (order_type == ORDER_TYPE_BUY) ? SymbolInfoDouble(symbol, SYMBOL_ASK) : SymbolInfoDouble(symbol, SYMBOL_BID);
   double sl = (order_type == ORDER_TYPE_BUY) ? price - stop_distance : price + stop_distance;
   double tp = (order_type == ORDER_TYPE_BUY) ? price + stop_distance * InpRewardRisk : price - stop_distance * InpRewardRisk;
   double lots = CalculateLots(symbol, stop_distance);
   if(lots <= 0)
      return;

   bool ok = false;
   if(order_type == ORDER_TYPE_BUY)
      ok = trade.Buy(lots, symbol, price, sl, tp, "AI_GOLD_RESEARCH breakout");
   else
      ok = trade.Sell(lots, symbol, price, sl, tp, "AI_GOLD_RESEARCH breakout");

   if(ok)
      trades_today++;
}

double CalculateLots(string symbol, double stop_distance)
{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_money = balance * InpRiskPercent / 100.0;
   double tick_size = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   double tick_value = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double volume_min = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double volume_max = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   double volume_step = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   if(tick_size <= 0 || tick_value <= 0 || volume_step <= 0)
      return 0.0;

   double risk_per_lot = (stop_distance / tick_size) * tick_value;
   if(risk_per_lot <= 0)
      return 0.0;

   double lots = risk_money / risk_per_lot;
   lots = MathFloor(lots / volume_step) * volume_step;
   lots = MathMax(volume_min, MathMin(volume_max, lots));
   return lots;
}

void ManageTimeExit(string symbol)
{
   datetime now = TimeCurrent();
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != symbol || PositionGetInteger(POSITION_MAGIC) != InpMagic)
         continue;
      datetime open_time = (datetime)PositionGetInteger(POSITION_TIME);
      if(now - open_time >= InpMaxHoldingHours * 3600)
         trade.PositionClose(ticket);
   }
}
